2887: 2887.cpp
	g++ -o $@ -O2 $^ -std=c++11

1647: 1647.cpp
	g++ -o $@ -O2 $^ -std=c++11

1992: 1992.cpp
	g++ -o $@ -O2 $^ -std=c++11

kruscal: kruscal.cpp
	g++ -o $@ -O2 $^ -std=c++11

tri: trigraph.cpp
	g++ -o $@ -O2 $^ -std=c++11

tree: treeradius_dp.cpp
	g++ -o $@ -O2 $^ -std=c++11

all: tri