7574 : 7574.cpp
	g++ -o $@ -O2 $^ -std=c++11

2261 : 2261.cpp
	g++ -o $@ -O2 $^ -std=c++11

sweepline: sweepline.cpp
	g++ -o $@ -O2 $^ -std=c++11

2357 : 2357.cpp
	g++ -o $@ -O2 $^ -std=c++11
	
2042b: 2042_bit.cpp
	g++ -o $@ -O2 $^ -std=c++11

2042: 2042.cpp
	g++ -o $@ -O2 $^ -std=c++11

segtree: segtree.cpp
	g++ -o $@ -O2 $^ -std=c++11

2206: 2206.cpp
	g++ -o $@ -O2 $^ -std=c++11

2178: 2178.cpp
	g++ -o $@ -O2 $^ -std=c++11

all: 2178